version: "3.8"

services:
  plutus:
    container_name: plutus
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      plutusnet:
        ipv4_address: 172.16.0.20

    restart: always
    env_file:
      - secret.env

networks:
  plutusnet:
    name: plutus_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
